name: Check pull request
on:
  pull_request:
    # we'll also run this when pull requests to develop are opened
    branches: [ develop ]

jobs:
  Build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
        Solution_Name: Revit_glTF_Exporter.sln
    outputs:
      Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }} 
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}   
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore nuGet packages
        run: nuget restore Revit_glTF_Exporter.sln 

      - name: Run MSBuild
        id: run-msbuild
        run: |
          msbuild Revit_glTF_Exporter.sln /t:Clean,Build /p:platform="Any CPU" /p:Configuration=Release

      - name: Run tests
        id: run-tests
        run: |
          dotnet test
          
     

