name: Deploy to Production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.5.0'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
      id: gitversion

    - name: Append Run Number to Version
      run: echo "FULL_VERSION=${{ steps.gitversion.outputs.MajorMinorPatch }}.${{ github.run_number }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Use environment variable
      run: echo "The value of the FULL_VERSION is $env:FULL_VERSION"

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6

    - name: Restore NuGet Packages
      run: nuget restore Revit_glTF_Exporter.sln

    - name: Install WiX Toolset
      run: choco install wixtoolset
    
    - name: Setting new version to the App.config file
      run: |
        (Get-Content Common_glTF_Exporter/App.config) -replace 'key="version" value="[^"]+"', "key=`"version`" value=`"$env:FULL_VERSION`"" | Out-File -encoding ASCII Common_glTF_Exporter/App.config

    - name: Replace strings in the code
      run: |
        (Get-Content GltfInstaller/Program.cs) -replace '0.0.0.0', $env:FULL_VERSION | Out-File -encoding ASCII GltfInstaller/Program.cs

    - name: Build and Publish App
      run: msbuild Revit_glTF_Exporter.sln /t:Clean,Build /p:platform="Any CPU" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.FULL_VERSION }}
        release_name: GLTF Exporter v${{ env.FULL_VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .\GltfInstaller\Leia - glTF exporter ${{ env.FULL_VERSION }}.msi
        asset_name: Leia-glTF exporter ${{ env.FULL_VERSION }}.msi
        asset_content_type: application/zip
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.EVERSE_AWS_S3_BUCKET_SECRET_KEY_ID }}
        aws-secret-access-key: ${{ secrets.EVERSE_AWS_S3_BUCKET_SECRET_KEY_SECRET }}
        aws-region: us-east-1

    - name: Upload file to S3
      run: |
        aws s3 cp .\GltfInstaller\Leia - glTF exporter $env:FULL_VERSION.msi s3://${{ secrets.EVERSE_INSTALLER_BUCKET_NAME }}/e-verse/LeiaGltfExporter

        