name: Deploy to Production

on:
  push:
    # this will cause the action to run on pushes to main
    branches: [ "master" ]

jobs:

  build:
  
    # The type of runner that the job will run on
    runs-on: windows-latest 
    env:
        Solution_Name: Revit_glTF_Exporter.sln
    outputs:
      Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }} 
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}   
     
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build   
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          4.7.x
          4.8.x
    - run: dotnet build --configuration Release Revit_glTF_Exporter

    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\ISCC.exe" ".\GLTFExporter.Installer\InstallScript.iss"
      shell: cmd
      
    - name: Upload the installer as an artifact
      uses: actions/upload-artifact@v2      
      with:
        path: "GLTFExporter.Installer/Installer/GTLFExporter.exe"
        name: wininstaller-innosetup
