name: Deploy to Production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: Revit_glTF_Exporter.sln
    outputs:
      Version: ${{ steps.gitversion.outputs.assemblySemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.5.0'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
      id: gitversion

    - name: Display GitVersion outputs
      run: |
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "AssemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"

    - name: Append Run Number to Version
      run: echo "FULL_VERSION=${{ steps.gitversion.outputs.MajorMinorPatch }}.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6

    - name: Restore NuGet Packages
      run: nuget restore Revit_glTF_Exporter.sln

    - name: Install WiX Toolset
      run: choco install wixtoolset

    - name: Set environment variable
      env:
        VERSION_VARIABLE: "2.0.0.0"

    - name: Use environment variable
      run: |
        echo "The value of the test variable is $env:TEST_VERSION"
      env:
        TEST_VERSION: ${{ env.test }}
    
    - name: Setting new version to the App.config file
      run: |
        (Get-Content Common_glTF_Exporter/App.config) -replace 'key="version" value="[^"]+"', "key=`"version`" value=`"$VERSION_VARIABLE`"" | Out-File -encoding ASCII Common_glTF_Exporter/App.config

    - name: Replace strings in the code
      run: |
        (Get-Content GltfInstaller/Program.cs) -replace '0.0.0.0', $VERSION_VARIABLE | Out-File -encoding ASCII GltfInstaller/Program.cs

    - name: Build and Publish App
      run: msbuild Revit_glTF_Exporter.sln /t:Clean,Build /p:platform="Any CPU" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v$$VERSION_VARIABLE
        release_name: GLTF Exporter $VERSION_VARIABLE
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: .\GltfInstaller\Leia - glTF exporter $VERSION_VARIABLE.msi
        asset_name: Leia - glTF exporter $VERSION_VARIABLE.msi
        asset_content_type: application/zip
